### ISSUE TITLE
Storing ArgoCD Application definition in Git

### ISSUE THREAD

**Issue by baijum** [openshift-app-service-poc/sbo-test-station#1]

**Comment by shruthihub** [comment]
The manifest that is created while adding new application from UI can be improvised by using a yaml file.
We can use declaritve setup of argocd application.

The application spec is : 

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ''
spec:
  destination:
    name: ''
    namespace: ''
    server: ''
  source:
    path: ''
    repoURL: ''
    targetRevision: HEAD
  project: ''
```

Command used to deploy : 
kubectl apply -n <namespace> -f application.yaml 

Argo CD will start deploying the guestbook application

For creating an application from a Chart , chart attribute must be specified instead of the path attribute within spec.source.:
```
`spec:
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo
`
```
Sample application.yaml - https://argo-cd.readthedocs.io/en/stable/operator-manual/application.yaml

So the yaml file can be stored in git as per the best practice

**Comment by baijum** [comment]
Please send a PR with the changes.

**Comment by shruthihub** [comment]
This is the manifest created for UI create application for rds.

```
project: default
source:
  repoURL: 'https://github.com/openshift-app-service-poc/sbo-test-station.git'
  path: rds
  targetRevision: HEAD
  helm:
    valueFiles:
      - values-test.yaml
destination:
  server: 'https://kubernetes.default.svc'
  namespace: rds

```
